### ISSUE TITLE
List timestamps for particular bird sounds

### ISSUE THREAD

**Issue by forthrin** [davipatti/birdbrain#1]
Looking for a utility that can list timestamps each time a particular bird sound (magpie, crow, seagull) occurs in an audio file, eg.

```
$ identify --bird=magpie audio.wav
..
01:23:45
01:23:49
etc.
```

Can this utility can be used for this, or which ones are the simplest for the purpose?

**Comment by davipatti** [comment]
This project not have this functionality. It was was an educational side project for me and is not under development.
